# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy UI to Azure Blob Storage

on:
#  workflow_run:
#    workflows: [ "Tests" ]
#    branches: 
#      - main
#    types:
#      - completed

  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ["ubuntu-latest"]
    container:
      image: node:20
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Restore dependencies
        run: npm install
        working-directory: ./UserInterface      
      - name: Build app
        run: npm rum build
        working-directory: ./UserInterface
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ui
          path: UserInterface/dist/user-interface/browser

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'productionui'

    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: ui
          path: dist
          
          
      - name: Deploy to SWA
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'dist'
          api_location: ''
          output_location: ''
          skip_app_build: true