# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy UI to Azure Blob Storage

on:
  
  push:
    branches:
      - day33
  workflow_dispatch:
#    
#  workflow_run:
#    workflows: [ "Tests" ]
#    branches: 
#      - main
#    types:
#      - completed

jobs:
  build:
    runs-on: ["ubuntu-latest"]
    container:
      image: node:20
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Restore dependencies
        run: npm install
        working-directory: ./UserInterface      
      - name: Build app
        run: npm rum build
        working-directory: ./UserInterface
      - name: Test
        run: ls -I node_modules -LR

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'productionui'

    steps:
      - name: Copy files
        uses: ulaval/azure-blob-copy-action@v1
        with:
          action: upload
          connection_string: ${{ secrets.BLOB_CONNECTION_STRING }}
          container_name: $web
          local_directory: UserInterface/dist/user-interface/browser
          http_headers: |            
            - glob: "**/*"
              headers:
                Cache-Control: public, max-age=120, s-maxage=180, proxy-revalidate