# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - checkers100

on:
  push:
    branches:
      - day33
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6edf29570397423daa5df50ea22f1c7a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b459234269f6442b8fe177481df7d1af }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_6edf29570397423daa5df50ea22f1c7a }}/checkers:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'checkers100'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5d8f0bb610e94d5e80c14566b3ad725d }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_6edf29570397423daa5df50ea22f1c7a }}/checkers:${{ github.sha }}'